# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(480, 300))
        MainWindow.setBaseSize(QtCore.QSize(480, 300))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("あんずもじ")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resource/image/photo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 302))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(20, 10, 20, 20)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pixmap_guest = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pixmap_guest.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixmap_guest.sizePolicy().hasHeightForWidth())
        self.pixmap_guest.setSizePolicy(sizePolicy)
        self.pixmap_guest.setMaximumSize(QtCore.QSize(80, 80))
        self.pixmap_guest.setAutoFillBackground(False)
        self.pixmap_guest.setStyleSheet("")
        self.pixmap_guest.setText("")
        self.pixmap_guest.setTextFormat(QtCore.Qt.AutoText)
        self.pixmap_guest.setPixmap(QtGui.QPixmap("../resource/image/photo.jpg"))
        self.pixmap_guest.setScaledContents(True)
        self.pixmap_guest.setWordWrap(False)
        self.pixmap_guest.setObjectName("pixmap_guest")
        self.verticalLayout_4.addWidget(self.pixmap_guest)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.lbl_guest_comment = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_guest_comment.sizePolicy().hasHeightForWidth())
        self.lbl_guest_comment.setSizePolicy(sizePolicy)
        self.lbl_guest_comment.setMinimumSize(QtCore.QSize(0, 120))
        self.lbl_guest_comment.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("あんずもじ")
        font.setPointSize(14)
        self.lbl_guest_comment.setFont(font)
        self.lbl_guest_comment.setStyleSheet("background-color: rgba(0, 170, 127, 120);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 14px;\n"
"border-color: white;\n"
"padding: 4px;")
        self.lbl_guest_comment.setText("")
        self.lbl_guest_comment.setScaledContents(False)
        self.lbl_guest_comment.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_guest_comment.setWordWrap(True)
        self.lbl_guest_comment.setObjectName("lbl_guest_comment")
        self.horizontalLayout_8.addWidget(self.lbl_guest_comment)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lbl_guest_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_guest_name.sizePolicy().hasHeightForWidth())
        self.lbl_guest_name.setSizePolicy(sizePolicy)
        self.lbl_guest_name.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_guest_name.setMaximumSize(QtCore.QSize(1000, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_guest_name.setFont(font)
        self.lbl_guest_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_guest_name.setObjectName("lbl_guest_name")
        self.verticalLayout.addWidget(self.lbl_guest_name)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lbl_voiceroid_reply = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_voiceroid_reply.sizePolicy().hasHeightForWidth())
        self.lbl_voiceroid_reply.setSizePolicy(sizePolicy)
        self.lbl_voiceroid_reply.setMinimumSize(QtCore.QSize(0, 120))
        self.lbl_voiceroid_reply.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("あんずもじ")
        font.setPointSize(14)
        self.lbl_voiceroid_reply.setFont(font)
        self.lbl_voiceroid_reply.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lbl_voiceroid_reply.setStyleSheet("background-color:rgb(238, 213, 244);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 14px;\n"
"border-color: white;\n"
"padding: 4px;")
        self.lbl_voiceroid_reply.setText("")
        self.lbl_voiceroid_reply.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_voiceroid_reply.setWordWrap(True)
        self.lbl_voiceroid_reply.setObjectName("lbl_voiceroid_reply")
        self.horizontalLayout_11.addWidget(self.lbl_voiceroid_reply)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pixmap_voiceroid = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pixmap_voiceroid.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixmap_voiceroid.sizePolicy().hasHeightForWidth())
        self.pixmap_voiceroid.setSizePolicy(sizePolicy)
        self.pixmap_voiceroid.setMaximumSize(QtCore.QSize(80, 80))
        self.pixmap_voiceroid.setAutoFillBackground(False)
        self.pixmap_voiceroid.setStyleSheet("")
        self.pixmap_voiceroid.setText("")
        self.pixmap_voiceroid.setTextFormat(QtCore.Qt.AutoText)
        self.pixmap_voiceroid.setPixmap(QtGui.QPixmap("../resource/image/yukari.png"))
        self.pixmap_voiceroid.setScaledContents(True)
        self.pixmap_voiceroid.setWordWrap(False)
        self.pixmap_voiceroid.setObjectName("pixmap_voiceroid")
        self.verticalLayout_5.addWidget(self.pixmap_voiceroid)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ぼいれす！"))
        self.lbl_guest_name.setText(_translate("MainWindow", "puuuii >> 結月ゆかり"))

